<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-INQUNRP" ignored="0" name="login " tests="4" failures="1" timestamp="2021-05-29T15:56:28 EDT" time="0.185" errors="0">
  <testcase name="userNameTest" time="0.018" classname="com.ChaseBankTestNgListeners.LoginTest"/>
  <testcase name="passwordTest" time="0.004" classname="com.ChaseBankTestNgListeners.LoginTest"/>
  <testcase name="submitTest" time="0.013" classname="com.ChaseBankTestNgListeners.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
at com.ChaseBankTestNgListeners.LoginTest.submitTest(LoginTest.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- submitTest -->
  <testcase name="forgetLinkTest" time="0.0" classname="com.ChaseBankTestNgListeners.LoginTest">
    <skipped/>
  </testcase> <!-- forgetLinkTest -->
</testsuite> <!-- login  -->
